### PR TITLE
add append, appendString, and appendBuffer methods (closes #1)

### LINKED ISSUE #1: Inline with needs of vinyl-sourcemap, etc
@jonschlinkert This is awesome.  I was just looking for replacements for `detect-newline` and `strip-bom` and I find you created said replacements 3 years ago.  So many ❤️ s

### PR DESCRIPTION
**Pull request by doowb**
Adds `append`, `appendString`, and `appendBuffer` methods discussed in #1.
Adds unit tests for scenarios discussed.

Doing the PR against the dev branch since that already has a PR to master.

### CODE REVIEW

**Comment by jonschlinkert** [comment]
@doowb thanks! 

@phated does this address what you needed?

**Comment by phated** [comment]
Reviewed the `appendBuffer` and I think it handles all the cases I thought of.  Windows tests failing though?

**Comment by doowb** [comment]
> Windows tests failing though?

I think some of the `normalizeEOL` tests are failing because the custom eol isn't passed in. I'll update those, then they'll get pulled into the `dev` branch.

**Comment by jonschlinkert** [comment]
@doowb feel free to merge and publish when you think it's ready, thanks!

**Pull request merged**
